### ISSUE TITLE
cài plugin vào trình duyệt

### ISSUE THREAD

**Issue by dangvantu99CM** [vuxuanvn/Quan-Ly-Dat-Hang-Trung-Quoc#14]

**Comment by dangvantu99CM** [comment]
uân m tìm hiểu cách thức để viết Plugin để cài vào trình duyệt , xong viết ra bản word

**Comment by dangvantu99CM** [comment]
Xuân m tìm hiểu cách thức để viết Plugin để cài vào trình duyệt , xong viết ra bản word

**Comment by vuxuanvn** [comment]
T có xem qua mấy cái extension của các trang web tương tự rồi. Mấy cái extension đó chỉ là điều hướng trang web thôi. Không phải crawl dữ liệu. Tuần sau có thể xong.

**Comment by dangvantu99CM** [comment]
ok
