### ISSUE TITLE
Fix lại giao diện trang chủ

### ISSUE THREAD

**Issue by dangvantu99CM** [vuxuanvn/Quan-Ly-Dat-Hang-Trung-Quoc#15]
Xuân m sửa lại giao diện trang chủ nhé

**Comment by dangvantu99CM** [comment]
@vuxuanvn lm xong giao diện trang chủ chưa

**Comment by vuxuanvn** [comment]
Do t đang phải ôn thi nên giao diên index châm nhất là ngày mai sẽ xong

**Comment by dangvantu99CM** [comment]
ok m,cố gắng xong sớm
