### ISSUE TITLE
Viết Markdown và description

### ISSUE THREAD

**Issue by vuxuanvn** [vuxuanvn/Quan-Ly-Dat-Hang-Trung-Quoc#4]

**Comment by dangvantu99CM** [comment]
Chức năng chính cần làm của hệ thống:
1. Hệ thống Plugin cài đặt trên các trình duyệt
- Hiển thị giao diện đặt hàng trên trang web của Taobao,Tmall
- Tính năng : plugin lấy tin mua hàng trên Taobao,Tmall
- Hiển thị số tiền quy đổi ghi chú
-Đặt hàng: lấy thông tin hàng hóa  trên Taobao,Tmall
-Xem giỏ hàng
-Thanh toán...
2. Quản trị khách hàng , đơn hàng dành cho quản trị viên
 - Quản lý dữ liệu khách hàng (tài khoản)
-  Quản lý đơn hàng đã đặt của khách hàng
